version: 0.0.{build}
os: Visual Studio 2015
configuration: Debug
            
install:
- cmd: choco install docfx
- git submodule update --init --recursive

before_build:
- cmd: nuget restore .\src\Buildron\Buildron.ModSdk\Buildron.ModSdk.sln

build:
  project: .\src\Buildron\Buildron.ModSdk\Buildron.ModSdk.sln
    
after_build:
- cmd: >-
    cd  .\docs\docfx_project
    
    docfx

test: off

artifacts:
  - path: .\docs\docfx_project\
    name: docfx_project.zip
